title: MacPass
description: A KeePass client for OS X
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/mstarke/MacPass/zipball/master
  tar_url: https://github.com/mstarke/MacPass/tarball/master
  
gems:
  - jekyll-mentions
